/**
 * 服务器端合约分析器
 * ==================
 * 与 contractAnalyzer.ts（浏览器端）功能相同，但：
 * - 不依赖 localStorage（配置通过函数参数传入）
 * - 使用 Provider 抽象层（src/services/llm/client.ts）调用 LLM
 * - 供 Agent API（/api/agent/audit）调用
 */

import type { ContractFile } from "@/types/blockchain";
import { mergeContractContents } from "@/utils/contractFilters";
import { SECURITY_AUDIT_PROMPT } from "@/services/audit/prompts";
import { createPromptWithSupperPrompt } from "@/utils/prompts";
import { createPromptWithLanguage } from "@/utils/language";
import { chatCompletion, chatCompletionStream } from "@/services/llm/client";
import type { LLMProvider } from "@/services/llm/types";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

export interface AgentAIConfig {
  provider: LLMProvider;
  model: string;
  language: string;
  superPrompt: boolean;
}

export interface ServerAnalysisResult {
  report: { analysis: string };
  raw?: unknown;
}

// ---------------------------------------------------------------------------
// 工具函数
// ---------------------------------------------------------------------------

function formatAIResponse(content: string): string {
  if (!content) return "";
  let formatted = content;
  formatted = formatted.replace(/(### [^\n]+)(\n\*\*)/g, "$1\n$2");
  formatted = formatted.replace(/```markdown/g, "");
  formatted = formatted.replace(/\n{3,}/g, "\n\n");
  return formatted;
}

function buildPrompt(
  files: ContractFile[],
  contractName: string | undefined,
  config: AgentAIConfig,
  isMultiFile: boolean
): string {
  const mergedCode = mergeContractContents(files, !isMultiFile);
  if (!mergedCode) throw new Error("No valid contract code to analyze");

  let prompt = createPromptWithLanguage(
    SECURITY_AUDIT_PROMPT
      .replace("${mergedCode}", mergedCode)
      .replace(
        "${params.contractName ? params.contractName : ''}",
        contractName || ""
      ),
    config.language
  );

  if (config.superPrompt) {
    prompt = createPromptWithSupperPrompt(prompt);
  }

  return prompt;
}

const SYSTEM_MSG =
  "You are a smart contract security auditor. Return findings in the requested markdown structure with clear, concrete locations and recommendations.";

// ---------------------------------------------------------------------------
// 同步分析（非流式）
// ---------------------------------------------------------------------------

export async function analyzeContractServer(params: {
  files: ContractFile[];
  contractName?: string;
  config: AgentAIConfig;
  signal?: AbortSignal;
  isMultiFile?: boolean;
}): Promise<ServerAnalysisResult> {
  const maxRetries = 3;
  let retryCount = 0;
  let lastError: unknown;

  while (retryCount < maxRetries) {
    try {
      if (params.signal?.aborted) throw new Error("Analysis cancelled");
      if (!params.files?.length) throw new Error("No contract files to analyze");

      const prompt = buildPrompt(
        params.files,
        params.contractName,
        params.config,
        !!params.isMultiFile
      );

      const { content, raw } = await chatCompletion(
        {
          provider: params.config.provider,
          model: params.config.model,
          messages: [
            { role: "system", content: SYSTEM_MSG },
            { role: "user", content: prompt },
          ],
          temperature: 0.5,
        },
        params.signal
      );

      const analysis =
        "# Generated by ChainVine (Agent API)\n\n" + formatAIResponse(content);

      return { report: { analysis }, raw };
    } catch (error: unknown) {
      if (
        (error instanceof Error && error.name === "AbortError") ||
        params.signal?.aborted
      ) {
        throw new Error("Analysis cancelled");
      }

      // 不可恢复错误（4xx）不重试 —— 参考 RFC 9110 §15.5
      const msg = error instanceof Error ? error.message : "";
      if (msg.includes("402") || msg.includes("401") || msg.includes("403")) {
        throw error;
      }

      lastError = error;
      retryCount++;
      if (retryCount < maxRetries) {
        await new Promise((r) => setTimeout(r, retryCount * 2000));
        continue;
      }

      throw new Error(
        `Analysis failed after ${maxRetries} attempts: ${
          lastError instanceof Error ? lastError.message : "Unknown error"
        }`
      );
    }
  }

  throw new Error("Unexpected error: analysis failed");
}

// ---------------------------------------------------------------------------
// 流式分析（StreamAI）
// ---------------------------------------------------------------------------

/**
 * 返回一个 ReadableStream<string>，调用方可以逐 chunk 转发给客户端（SSE / fetch stream）。
 * 流结束后，调用方可用 collected 拼接完整报告再做融合。
 */
export function analyzeContractServerStream(params: {
  files: ContractFile[];
  contractName?: string;
  config: AgentAIConfig;
  signal?: AbortSignal;
  isMultiFile?: boolean;
}): ReadableStream<string> {
  if (!params.files?.length) {
    throw new Error("No contract files to analyze");
  }

  const prompt = buildPrompt(
    params.files,
    params.contractName,
    params.config,
    !!params.isMultiFile
  );

  return chatCompletionStream(
    {
      provider: params.config.provider,
      model: params.config.model,
      messages: [
        { role: "system", content: SYSTEM_MSG },
        { role: "user", content: prompt },
      ],
      temperature: 0.5,
    },
    params.signal
  );
}
